/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Servidor;

/**
 *
 * @author Esteban
 */
public class JFrameServidor extends javax.swing.JFrame {

    ServidorMundos servidor;
    /**
     * Creates new form JFrameServidor
     */
    public JFrameServidor() {
        initComponents();
        servidor = new ServidorMundos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaMensajesServidor = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaMensajesServidor.setColumns(20);
        txaMensajesServidor.setRows(5);
        jScrollPane1.setViewportView(txaMensajesServidor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int cantidadJugadores = 2;
        DecidirJugador decision = new DecidirJugador();
        cantidadJugadores = decision.decidirCantidadJugadores();
        System.out.print(cantidadJugadores);
        
        JFrameServidor server = new JFrameServidor();
        server.setVisible(true);
        //corre el servidor
        server.servidor.runServer(cantidadJugadores);
    }
    
    public void desplegarMensaje (String texto)
    {
        txaMensajesServidor.append(texto+"\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaMensajesServidor;
    // End of variables declaration//GEN-END:variables
}



